app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
// Authentication Routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Authenticate certificate
Route::get('autenticar', 'Auth\AuthController@getAuthenticateCertificate');
Route::post('autenticar', 'Auth\AuthController@postAuthenticateCertificate');

// Registration Routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

Route::post('mail/contact', 'EmailController@sendEmailContact');
Route::get('state/{id}/cities', 'StateController@cities');

Route::get('/', 'Auth\AuthController@getLogin');

Route::group(array('middleware' => 'auth'), function(){

  $closingDate = "2018-08-16 15:00:00";

  $isClosed = time() > strtotime($closingDate);

  if(!$isClosed) {
    Route::get('work/create_step/{step}', 'WorkController@createStep')->where(['step' => '[1-4]']);
    Route::post('work/store_step/{step}', 'WorkController@storeStep')->where(['step' => '[1-4]']);
  }

  Route::get('work/review', 'WorkController@review');
  Route::get('work/confirm', 'WorkController@confirm');
  Route::get('work/discard', 'WorkController@discard');

  Route::resource('work', 'WorkController');
  Route::get('work/print/{id}', ['as' => 'work.print', 'uses' => 'WorkController@printWork']);
  Route::get('school/find/{state_id}/{city_id}/{query?}', 'SchoolController@query');
  Route::get('school/{school_id}/adm_dept', 'SchoolController@getAdministrativeDepartment');
  Route::get('category/{category_id}/years', 'CategoryController@getYears');

  Route::get('certificate','CertificateController@index');
  Route::get('certificate/teacher/{work_id}',['as' => 'certificate.teacher', 'uses' => 'CertificateController@teacherCertificate']);
  Route::get('certificate/student/{work_id}',['as' => 'certificate.student', 'uses' => 'CertificateController@studentCertificate']);
  Route::get('certificate/winnerStudent/{work_id}',['as' => 'certificate.winner_student', 'uses' => 'CertificateController@winnerStudentCertificate']);
  Route::get('certificate/winnerTeacher/{work_id}',['as' => 'certificate.winner_teacher', 'uses' => 'CertificateController@winnerTeacherCertificate']);

  Route::group(array('middleware' => 'national_coodinator'), function() {
    Route::resource('city', 'CityController');
    Route::resource('state', 'StateController');
    Route::resource('regional', 'RegionalController');
    Route::resource('subject', 'SubjectController');
    Route::resource('academic_qualification', 'AcademicQualificationController');
    Route::resource('edition', 'EditionController');
    Route::resource('school', 'SchoolController');
    Route::resource('category', 'CategoryController');
    Route::resource('category_year', 'CategoryYearController');
    Route::get('edition/activate/{id}', ['as' => 'edition.activate', 'uses' => 'EditionController@activate']);
    Route::get('work/validate/{id}', ['as' => 'work.validate', 'uses' => 'WorkController@validateWork']);
    Route::get('work/winner/{id}', ['as' => 'work.winner', 'uses' => 'WorkController@setIsWinner']);
    Route::get('users/search-teachers', 'UserController@searchTeachers');
  });

  Route::group(array('middleware' => 'admin'), function() {
    Route::get('report/works', ['as' => 'report.works', 'uses' => 'ReportController@works']);
    Route::get('report/teachers', ['as' => 'report.teachers', 'uses' => 'ReportController@teachers']);
    Route::resource('user', 'UserController');
    Route::get('user/block/{id}', ['as' => 'user.block', 'uses' => 'UserController@block']);
    Route::get('user/unblock/{id}', ['as' => 'user.unblock', 'uses' => 'UserController@unblock']);
    Route::post('work/update_status/{id}', ['as' => 'work.update_status', 'uses' => 'WorkController@updateStatus']);
    Route::get('email', 'EmailController@compose');
    Route::post('email/send', 'EmailController@sendEmail');
    Route::post('email/upload', 'EmailController@upload');
  });

  Route::get('home', function() {

    if(Auth::user()->role_id == \OBSMA\Role::TEACHER) {

      $closingDate = "2018-08-16 15:00:00";

      $isClosed = time() > strtotime($closingDate);

      $showCertificates = \OBSMA\Work::where('is_valid',1)->where('teacher_id',Auth::user()->userable_id)->count() > 0;
      return view('home', compact('showCertificates', 'isClosed'));
    } else {

      if (Session::has('success')) {
        Session::keep('success');
      }

      if (Session::has('warning')) {
        Session::keep('warning');
      }

      if (Session::has('danger')) {
        Session::keep('danger');
      }
      
      return redirect('report/works');
    }
  });

  Route::get('profile', 'ProfileController@getProfile');
  Route::post('profile/update', 'ProfileController@updateProfile');
  Route::get('profile/password', 'ProfileController@getPassword');
  Route::post('profile/update_password', 'ProfileController@updatePassword');


});

app/State.php
<?php

namespace OBSMA;

use Illuminate\Database\Eloquent\Model;

class State extends Model
{
     protected $fillable = ['name'];

     public function cities()
     {
        return $this->hasMany(City::class);
     }

     public function regional()
     {
        return $this->belongsTo(Regional::class);
     }

     public function getCitiesPaginatedAttribute()
     {
        return $this->cities()->paginate(10);
     }

     public function getCitiesOrderedAttribute()
     {
        return $this->cities()->orderBy('name', 'asc');
     }
}

app/Http/Controllers/StateController.php
<?php

namespace OBSMA\Http\Controllers;

use Illuminate\Http\Request;

use OBSMA\Http\Requests;
use OBSMA\Http\Controllers\Controller;

use OBSMA\State;
use OBSMA\Regional;

class StateController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $states = State::orderBy('name')->paginate(15);

      return view('state.index', compact('states'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $state = new State;
      $regionals = Regional::lists('name', 'id');

      return view('state.create', compact('state','regionals'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $this->validate($request, [
        'name' => 'required',
        'acronym' => 'required',
        'regional_id' => 'integer',
      ]);

      State::create([
        'name' => $request->name,
        'acronym' => $request->acronym,
        'regional_id' => $request->regional_id
      ]);

      return redirect('/state')->with('success', 'Estado cadastrado com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $state = State::findOrFail($id);

      return view('state.show', compact('state'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $state = State::findOrFail($id);
      $regionals = Regional::lists('name', 'id');

      return view('state.edit', compact('state','regionals'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $state = State::findOrFail($id);

      $this->validate($request, [
        'name' => 'required',
        'acronym' => 'required',
        'regional_id' => 'integer'
      ]);

      $state->acronym = $request->acronym;
      $state->name = $request->name;
      $state->regional_id = $request->regional_id;

      $state->save();
      return redirect('/state')->with('success', 'Estado atualizado com sucesso!');
    }

    public function cities($id)
    {
      $state = State::findOrFail($id);
      return response()->json( ['cities' => $state->citiesOrdered->select('id','name')->get()->toArray()]);
    }

}

resources/views/state/create.blade.php
@extends('layouts.internal')

@section('header_title')
Novo Estado
@endsection

@section('content')
<div class="container-fluid">
  @include('state/form')
</div>
@endsection

resources/views/state/edit.blade.php
@extends('layouts.internal')

@section('header_title')
Editar Estado
@endsection

@section('content')
<div class="container-fluid">
  @include('state/form')
</div>
@endsection

resources/views/state/form.blade.php
{!! Form::model($state, array('route' => ($state->exists ? array('state.update', $state->id) : 'state.store'),'method' => ($state->exists ? 'PUT' : 'POST')) )!!}
  <div class="row">
    <div class="col-sm-6">
      <div class='form-group @if ($errors->has('acronym')) has-error @endif'>
        {!! Form::label('acronym', "* Sigla") !!}
        {!! Form::text('acronym', null,array('class' => 'form-control')) !!}
        @if ($errors->has('acronym')) <p class="help-block">{{ $errors->first('acronym') }}</p> @endif
      </div>
      <div class='form-group @if ($errors->has('name')) has-error @endif'>
        {!! Form::label('name', "* Nome") !!}
        {!! Form::text('name', null,array('class' => 'form-control')) !!}
        @if ($errors->has('name')) <p class="help-block">{{ $errors->first('name') }}</p> @endif
      </div>

      <div class='form-group @if ($errors->has('regional_id')) has-error @endif'>
        {!! Form::label('regional_id', "Regional") !!}
        {!! Form::select('regional_id', $regionals,  null, array('placeholder' => 'Selecione a regional...', 'class' => 'form-control state-selector')) !!}
        @if ($errors->has('regional_id')) <p class="help-block">{{ $errors->first('regional_id') }}</p> @endif
      </div>
    </div>
  </div>

  {!! Form::submit('Salvar', array('class' => 'btn btn-primary')) !!}
  {!! link_to('state', "Voltar", array('class' => 'btn btn-default')) !!}
{!! Form::close() !!}

resources/views/state/index.blade.php
@extends('layouts.internal')

@section('header_title')
Estados
@endsection

@section('content')
<div class="container-fluid">
  {!! link_to('state/create', "Novo", array('class' => 'btn btn-primary')) !!}
  <br>
  <br>

  <div class="row">
    <div class="col-xs-12 text-right">
      {!! "Mostrando <b>" . $states->count() . "</b> de <b>" . $states->total() . "</b> resultados" !!}
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Sigla</th>
            <th>Nome</th>
            <th>Regional</th>
            <th>Ações</th>
          </tr>
        </thead>
        <tbody>
          @forelse ($states as $state)
            <tr>
              <td>{{ $state->acronym }}</td>
              <td>{{ $state->name }}</td>
              <td>{{ $state->regional == null ? '' : $state->regional->name }}</td>
              <td>
                <a class="btn btn-xs btn-default" href="{{url('state',[$state])}}"> <i class="fa fa-eye"> </i> Ver </a>
                <a class="btn btn-xs btn-default" href="{{route('state.edit',[$state])}}"> <i class="fa fa-pencil"> </i> Editar </a>
              </td>
            </tr>
          @empty
            <tr>
              <td colspan="2">Nenhum estado cadastrado</td>
            </tr>
          @endforelse
        </tbody>
      </table>
    </div>
  </div>
  {!! $states->render() !!}
</div>
@endsection

resources/views/state/show.blade.php
@extends('layouts.internal')

@section('header_title')
Estado
@endsection

@section('content')
<div class="container-fluid">
  <fieldset>
    <legend>{{$state->name}}</legend>
    <div class="row">
      <div class="col-sm-6">
        <p><strong>Sigla:</strong> {{$state->acronym}} </p>
        <p><strong>Regional:</strong> {{$state->regional === null ? '' : $state->regional->name}} </p>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Cidades</th>
            </tr>
          </thead>
          <tbody>
            @forelse ($state->cities_paginated as $city)
              <tr>
                <td>{{ $city->name }}</td>
              </tr>
            @empty
              <tr>
                <td>Nenhuma cidade cadastrada</td>
              </tr>
            @endforelse
          </tbody>
        </table>
        {!! $state->cities_paginated->render() !!}
      </div>
    </div>
  </fieldset>

  {!! link_to('state', "Voltar", array('class' => 'btn btn-default')) !!}
  {!! link_to_route('state.edit', "Editar", array('id' => $state->id), array('class' => 'btn btn-default')) !!}
</div>
@endsection