app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
// Authentication Routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Authenticate certificate
Route::get('autenticar', 'Auth\AuthController@getAuthenticateCertificate');
Route::post('autenticar', 'Auth\AuthController@postAuthenticateCertificate');

// Registration Routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

Route::post('mail/contact', 'EmailController@sendEmailContact');
Route::get('state/{id}/cities', 'StateController@cities');

Route::get('/', 'Auth\AuthController@getLogin');

Route::group(array('middleware' => 'auth'), function(){

  $closingDate = "2018-08-16 15:00:00";

  $isClosed = time() > strtotime($closingDate);

  if(!$isClosed) {
    Route::get('work/create_step/{step}', 'WorkController@createStep')->where(['step' => '[1-4]']);
    Route::post('work/store_step/{step}', 'WorkController@storeStep')->where(['step' => '[1-4]']);
  }

  Route::get('work/review', 'WorkController@review');
  Route::get('work/confirm', 'WorkController@confirm');
  Route::get('work/discard', 'WorkController@discard');

  Route::resource('work', 'WorkController');
  Route::get('work/print/{id}', ['as' => 'work.print', 'uses' => 'WorkController@printWork']);
  Route::get('school/find/{state_id}/{city_id}/{query?}', 'SchoolController@query');
  Route::get('school/{school_id}/adm_dept', 'SchoolController@getAdministrativeDepartment');
  Route::get('category/{category_id}/years', 'CategoryController@getYears');

  Route::get('certificate','CertificateController@index');
  Route::get('certificate/teacher/{work_id}',['as' => 'certificate.teacher', 'uses' => 'CertificateController@teacherCertificate']);
  Route::get('certificate/student/{work_id}',['as' => 'certificate.student', 'uses' => 'CertificateController@studentCertificate']);
  Route::get('certificate/winnerStudent/{work_id}',['as' => 'certificate.winner_student', 'uses' => 'CertificateController@winnerStudentCertificate']);
  Route::get('certificate/winnerTeacher/{work_id}',['as' => 'certificate.winner_teacher', 'uses' => 'CertificateController@winnerTeacherCertificate']);

  Route::group(array('middleware' => 'national_coodinator'), function() {
    Route::resource('city', 'CityController');
    Route::resource('state', 'StateController');
    Route::resource('regional', 'RegionalController');
    Route::resource('subject', 'SubjectController');
    Route::resource('academic_qualification', 'AcademicQualificationController');
    Route::resource('edition', 'EditionController');
    Route::resource('school', 'SchoolController');
    Route::resource('category', 'CategoryController');
    Route::resource('category_year', 'CategoryYearController');
    Route::get('edition/activate/{id}', ['as' => 'edition.activate', 'uses' => 'EditionController@activate']);
    Route::get('work/validate/{id}', ['as' => 'work.validate', 'uses' => 'WorkController@validateWork']);
    Route::get('work/winner/{id}', ['as' => 'work.winner', 'uses' => 'WorkController@setIsWinner']);
    Route::get('users/search-teachers', 'UserController@searchTeachers');
  });

  Route::group(array('middleware' => 'admin'), function() {
    Route::get('report/works', ['as' => 'report.works', 'uses' => 'ReportController@works']);
    Route::get('report/teachers', ['as' => 'report.teachers', 'uses' => 'ReportController@teachers']);
    Route::resource('user', 'UserController');
    Route::get('user/block/{id}', ['as' => 'user.block', 'uses' => 'UserController@block']);
    Route::get('user/unblock/{id}', ['as' => 'user.unblock', 'uses' => 'UserController@unblock']);
    Route::post('work/update_status/{id}', ['as' => 'work.update_status', 'uses' => 'WorkController@updateStatus']);
    Route::get('email', 'EmailController@compose');
    Route::post('email/send', 'EmailController@sendEmail');
    Route::post('email/upload', 'EmailController@upload');
  });

  Route::get('home', function() {

    if(Auth::user()->role_id == \OBSMA\Role::TEACHER) {

      $closingDate = "2018-08-16 15:00:00";

      $isClosed = time() > strtotime($closingDate);

      $showCertificates = \OBSMA\Work::where('is_valid',1)->where('teacher_id',Auth::user()->userable_id)->count() > 0;
      return view('home', compact('showCertificates', 'isClosed'));
    } else {

      if (Session::has('success')) {
        Session::keep('success');
      }

      if (Session::has('warning')) {
        Session::keep('warning');
      }

      if (Session::has('danger')) {
        Session::keep('danger');
      }
      
      return redirect('report/works');
    }
  });

  Route::get('profile', 'ProfileController@getProfile');
  Route::post('profile/update', 'ProfileController@updateProfile');
  Route::get('profile/password', 'ProfileController@getPassword');
  Route::post('profile/update_password', 'ProfileController@updatePassword');


});

app/Regional.php
<?php

namespace OBSMA;

use Illuminate\Database\Eloquent\Model;

class Regional extends Model
{
  protected $fillable = [
    'name',
    'place',
    'address',
    'complement',
    'zip_code',
    'neighborhood',
    'city_id',
    'phone_number',
    'fax_number',
    'coordinator_name'
  ];

  public function city()
  {
     return $this->belongsTo(City::class);
  }

  public function states()
  {
     return $this->hasMany(State::class);
  }

  public function getStatesPaginatedAttribute()
  {
     return $this->states()->paginate(10);
  }
}

app/School.php
<?php

namespace OBSMA;

use Illuminate\Database\Eloquent\Model;

class School extends Model
{
    protected $fillable = [
        'name',
        'code',
        'year',
        'administrative_department',
        'type',
        'state_id',
        'city_id',
        'address',
        'neighborhood',
        'zip_code',
        'mailbox',
        'email',
        'phone_number'
    ];

    protected $dates = ['year'];

    public function city()
    {
        return $this->belongsTo(City::class);
    }

    public function state()
    {
        return $this->belongsTo(State::class);
    }

}

app/Http/Controllers/SchoolController.php
<?php

namespace OBSMA\Http\Controllers;

use Carbon\Carbon;
use Illuminate\Http\Request;

use Illuminate\Support\Facades\Input;
use OBSMA\Http\Requests;

use OBSMA\School;
use OBSMA\State;

class SchoolController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $schoolQuery = School::query();

        $request->session()->put('school_inputs', Input::except('_excel'));
        if ($request->s_name != "")
          $schoolQuery->where('schools.name', 'LIKE', "%{$request->s_name}%");

        if ($request->s_code != "")
          $schoolQuery->where('schools.code', 'LIKE', "%{$request->s_code}%");

        $request->flash();
        $schools = $schoolQuery->paginate(15);

        return view('school.index', compact('schools'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $school = new School;
      $states = State::lists('name', 'id');

      return view('school.create', compact('school','states'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $this->validate($request, [
        'code' => 'integer',
        'name' => 'required',
        'email' => 'email',
        'type' => 'required',
        'administrative_department' => 'required',
        'address' => 'required',
        'neighborhood' => 'required',
        'state_id' => 'integer|required',
        'city_id' => 'integer|required',
      ]);

      School::create(array_add($request->all(), 'year', Carbon::today()));

      return redirect('/school')->with('success', 'Escola cadastrada com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $school = School::findOrFail($id);

      return view('school.show', compact('school'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $school = School::findOrFail($id);
      $states = State::lists('name', 'id');

      return view('school.edit', compact('school','states'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $school = School::findOrFail($id);

      $this->validate($request, [
        'name' => 'required',
        'acronym' => 'required',
        'regional_id' => 'integer'
      ]);

      $school->acronym = $request->acronym;
      $school->name = $request->name;
      $school->regional_id = $request->regional_id;

      $school->save();
      return redirect('/school')->with('success', 'Estado atualizado com sucesso!');
    }

    public function query($state_id, $city_id, $query = null)
    {
        $schoolQuery = School::where(['state_id' => $state_id, 'city_id' => $city_id]);

        if ($query !== null)
            $schoolQuery->where('name', 'like', "%{$query}%");

        $schools = $schoolQuery->select('id', 'name')->get();
        return response()->json( ['schools' => $schools->toArray()] );
    }

    public function getAdministrativeDepartment($school_id)
    {
        $school = School::findOrFail($school_id);
        return response()->json( ['school' => $school] );

    }

}

resources/views/school/create.blade.php
@extends('layouts.internal')

@section('header_title')
Nova Escola
@endsection

@section('content')
<div class="container-fluid">
  @include('school/form')
</div>
@endsection

resources/views/school/edit.blade.php
@extends('layouts.internal')

@section('header_title')
Editar Escola
@endsection

@section('content')
<div class="container-fluid">
  @include('school/form')
</div>
@endsection

resources/views/school/form.blade.php
{!! Form::model($school, array('route' => ($school->exists ? array('school.update', $school->id) : 'school.store'),'method' => ($school->exists ? 'PUT' : 'POST'))) !!}
  <div class="row">
    <div class="col-sm-6 bg-">

      <div class='form-group @if ($errors->has('code')) has-error @endif'>
        {!! Form::label('code', "Código") !!}
        {!! Form::text('code', null,array('class' => 'form-control')) !!}
        @if ($errors->has('code')) <p class="help-block">{{ $errors->first('code') }}</p> @endif
      </div>

      <div class='form-group @if ($errors->has('name')) has-error @endif'>
        {!! Form::label('name', "* Nome") !!}
        {!! Form::text('name', null,array('class' => 'form-control')) !!}
        @if ($errors->has('name')) <p class="help-block">{{ $errors->first('name') }}</p> @endif
      </div>

      <div class='form-group @if ($errors->has('type')) has-error @endif'>
        {!! Form::label('type', "* Tipo") !!}
        {!! Form::select('type', ['Urbana' => 'Urbana', 'Rural' => 'Rural'], null,array('class' => 'form-control')) !!}
        @if ($errors->has('type')) <p class="help-block">{{ $errors->first('type') }}</p> @endif
      </div>

      <div class='form-group @if ($errors->has('administrative_department')) has-error @endif'>
        {!! Form::label('administrative_department', "* Dept. Administrativo") !!}
        {!! Form::select('administrative_department', ['Estadual' => 'Estadual', 'Federal' => 'Federal', 'Municipal' => 'Municipal', 'Particular' => 'Particular', 'Privada' => 'Privada'], null,array('class' => 'form-control')) !!}
        @if ($errors->has('administrative_department')) <p class="help-block">{{ $errors->first('administrative_department') }}</p> @endif
      </div>

      <div class='form-group @if ($errors->has('state_id')) has-error @endif'>
        {!! Form::label('state_id', "* Estado") !!}
        {!! Form::select('state_id', $states,  null, array('placeholder' => 'Selecione o estado...', 'class' => 'form-control state-selector')) !!}
        @if ($errors->has('state_id')) <p class="help-block">{{ $errors->first('state_id') }}</p> @endif
      </div>

      <div class='form-group @if ($errors->has('city_id')) has-error @endif'>
        {!! Form::label('city_id', "* Cidade") !!}
        {!! Form::select('city_id', ($school->exists ? $school->state->cities->sortBy('name')->lists('name','id') : []), null, array('placeholder' => 'Selecione a cidade...','class' => 'form-control city-selector')) !!}
        @if ($errors->has('city_id')) <p class="help-block">{{ $errors->first('city_id') }}</p> @endif
      </div>


    </div>

    <div class="col-sm-6">

      <div class='form-group @if ($errors->has('address')) has-error @endif'>
        {!! Form::label('address', "* Endereço") !!}
        {!! Form::text('address', null,array('class' => 'form-control')) !!}
        @if ($errors->has('address')) <p class="help-block">{{ $errors->first('address') }}</p> @endif
      </div>

      <div class='form-group @if ($errors->has('neighborhood')) has-error @endif'>
        {!! Form::label('neighborhood', "* Bairro") !!}
        {!! Form::text('neighborhood', null,array('class' => 'form-control')) !!}
        @if ($errors->has('neighborhood')) <p class="help-block">{{ $errors->first('neighborhood') }}</p> @endif
      </div>

      <div class='form-group @if ($errors->has('complement')) has-error @endif'>
        {!! Form::label('complement', "Complemento") !!}
        {!! Form::text('complement', null,array('class' => 'form-control')) !!}
        @if ($errors->has('complement')) <p class="help-block">{{ $errors->first('complement') }}</p> @endif
      </div>

      <div class='form-group @if ($errors->has('zip_code')) has-error @endif'>
        {!! Form::label('zip_code', "CEP") !!}
        {!! Form::text('zip_code', NULL, array('class' => 'form-control')) !!}
        @if ($errors->has('zip_code')) <p class="help-block">{{ $errors->first('zip_code') }}</p> @endif
      </div>

      <div class='form-group @if ($errors->has('email')) has-error @endif'>
        {!! Form::label('email', "Email") !!}
        {!! Form::text('email', null,array('class' => 'form-control')) !!}
        @if ($errors->has('email')) <p class="help-block">{{ $errors->first('email') }}</p> @endif
      </div>

      <div class='form-group @if ($errors->has('phone_number')) has-error @endif'>
        {!! Form::label('phone_number', "Telefone") !!}
        {!! Form::text('phone_number', null,array('class' => 'form-control phone_number')) !!}
        @if ($errors->has('phone_number')) <p class="help-block">{{ $errors->first('phone_number') }}</p> @endif
      </div>

    </div>
  </div>

  {!! Form::submit('Salvar', array('class' => 'btn btn-primary')) !!}
  {!! link_to('school', "Voltar", array('class' => 'btn btn-default')) !!}
{!! Form::close() !!}

resources/views/school/index.blade.php
@extends('layouts.internal')

@section('header_title')
Escolas
@endsection

@section('content')
<div class="container-fluid">

  <div class="row">
    <div class="col-sm-12">
      <div class="well">
        {!! Form::open(['method' => 'get', 'url' => 'school']) !!}

        <div class="row">
          <div class="col-sm-4">
            <div class="form-group">
              {!! Form::label('s_name', 'Nome: ', ['class' => 'control-label']) !!}
              {!! Form::text('s_name', old('s_name'), ['class' => 'form-control', 'placeholder' => 'Nome']) !!}
            </div>
          </div>
          <div class="col-sm-4">
            <div class="form-group">
              {!! Form::label('s_code', 'Código INEP: ', ['class' => 'control-label']) !!}
              {!! Form::text('s_code', old('s_code'), ['class' => 'form-control', 'placeholder' => 'Código INEP']) !!}
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-12">
            {!! Form::button("<i class='fa fa-search'></i> Pesquisar", ['id' => 'search', 'class' => 'btn btn-primary btn-lg']) !!}

            {!! link_to('school',"Todos", ['class' => 'btn btn-default btn-lg'])  !!}
          </div>
        </div>
        {!! Form::close() !!}
      </div>
    </div>
  </div>

  {!! link_to('school/create', "Novo", array('class' => 'btn btn-primary')) !!}
  <br>
  <br>

  <div class="row">
    <div class="col-xs-12 text-right">
      {!! "Mostrando <b>" . $schools->count() . "</b> de <b>" . $schools->total() . "</b> resultados" !!}
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Código INEP</th>
            <th>Ano</th>
            <th>Nome</th>
            <th>Estado</th>
            <th>Cidade</th>
            <th>Telefone</th>
            {{--<th>Ações</th>--}}
          </tr>
        </thead>
        <tbody>
          @forelse ($schools as $school)
            <tr>
              <td>{{ $school->code }}</td>
              <td>{{ $school->year->format('Y') }}</td>
              <td>{{ $school->name }}</td>
              <td>{{ $school->state->name }}</td>
              <td>{{ $school->city->name }}</td>
              <td>{{ $school->phone_number }}</td>
              <td>
                {{--<a class="btn btn-xs btn-default" href="{{url('school',[$school])}}"> <i class="fa fa-eye"> </i> Ver </a>--}}
                {{--<a class="btn btn-xs btn-default" href="{{route('school.edit',[$school])}}"> <i class="fa fa-pencil"> </i> Editar </a>--}}
                {{-- <a class="btn btn-xs btn-default" href="{{url('school',[$school])}}"> <i class="fa fa-eye"> </i> Ver </a> --}}
              </td>
            </tr>
          @empty
            <tr>
              <td colspan="2">Nenhuma escola cadastrada</td>
            </tr>
          @endforelse
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      {!! $schools->appends(Input::except('page'))->render() !!}
    </div>
  </div>

  {!! link_to('/', "Voltar", array('class' => 'btn btn-default')) !!}

</div>
@endsection

resources/views/school/show.blade.php
@extends('layouts.internal')

@section('header_title')
Regional
@endsection

@section('content')
<div class="container-fluid">
  <fieldset>
    <legend>{{$regional->name}}</legend>
    <div class="row">
      <div class="col-sm-6">
        <p><strong>Local:</strong> {{$regional->place}} </p>
        <p><strong>Endereço:</strong> {{$regional->address}} </p>
        <p><strong>Complemento:</strong> {{$regional->complement}} </p>
        <p><strong>Bairro:</strong> {{$regional->neighborhood}} </p>
        <p><strong>CEP:</strong> {{$regional->zip_code}} </p>
        <p class="text-lowercase text-capitalize"><strong>Cidade:</strong> {{$regional->city->name}} </p>
        <p class="text-capitalize"><strong>Estado:</strong> {{$regional->city->state->name}} </p>
      </div>
      <div class="col-sm-6">
        <p><strong>Coordenador:</strong> {{$regional->coordinator_name}} </p>
        <p><strong>Email:</strong> {{$regional->email}} </p>
        <p><strong>Telefone:</strong> {{$regional->phone_number}} </p>
        <p><strong>Fax:</strong> {{$regional->fax_number}} </p>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Estados</th>
            </tr>
          </thead>
          <tbody>
            @forelse ($regional->states_paginated as $state)
              <tr>
                <td>{{ $state->name }}</td>
              </tr>
            @empty
              <tr>
                <td>Nenhuma estado cadastrado</td>
              </tr>
            @endforelse
          </tbody>
        </table>
        {!! $regional->states_paginated->render() !!}
      </div>
    </div>
  </fieldset>

  {!! link_to('regional', "Voltar", array('class' => 'btn btn-default')) !!}
  {!! link_to_route('regional.edit', "Editar", array('id' => $regional->id), array('class' => 'btn btn-default')) !!}
</div>
@endsection